name: Build PHP MSI
on:
  workflow_dispatch:
    inputs:
      basename:
        description: 'Basename of PHP ZIP'
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    name: Build ${{github.event.inputs.basename}}.msi
    runs-on: windows-2022
    steps:
      - name: Checkout php-msi
        uses: actions/checkout@v4
      - name: Fetch PHP
        run: |
          curl -sLO https://windows.php.net/downloads/releases/${{github.event.inputs.basename}}.zip
          7z x -ophp ${{github.event.inputs.basename}}.zip
      - name: Generate WXS
        run: php -dshort_open_tag=1 wxsgen\wxsgen.php php php.wxs
      - name: Compile
        run: candle php.wxs
      - name: Link
        run: light -ext WixUIExtension -out ${{github.event.inputs.basename}}.msi php.wixobj
      - name: Install
        run: xcopy ${{github.event.inputs.basename}}.msi artifacts\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.basename}}
          path: artifacts
